spring:
  profiles:
    active: dev
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:./cgi_dev.db;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    platform: h2
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        jdbc.lob.non_contextual_creation: true
        dialect: org.hibernate.dialect.H2Dialect
    show-sql: true
    database: h2
  main:
    allow-bean-definition-overriding: true
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
      fail-on-empty-beans: false
    time-zone: UTC


logging:
  level:
    root: INFO
    org:
      hibernate: INFO

