version: '3'
services:
  postgres:
    container_name: postgres_container
    image: kartoza/postgis:12.0
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: demo
    volumes:
      - ./data/postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
  redis:
    container_name: redis_container
    image: redis:5.0.6
    command: redis-server --requirepass TfAbLrAYgWUZV4V3ukdfB4fGvHXwsv3w
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
    environment:
      REDIS_PASSWORD: TfAbLrAYgWUZV4V3ukdfB4fGvHXwsv3w
    restart: unless-stopped
volumes:
  postgres:
  redis:

